### PR TITLE
Add Radius Elnet tariff "B lav time"

### PR DESCRIPTION
**Pull request by nikobh**
I have added the B Lav Time tariff to the chargeowners.py and renamed "Radius" to "Radius C". When doing this change in my home installation it works great. This is my first online change, so I hope it works.

### CODE REVIEW

**Comment by MTrab** [comment]
And what is B used for?
I have only knowledge of C for private customers

**Comment by MTrab** [comment]
Other than that, this will introduce a major breaking change with the namechange for the original Radius entry, so I'm not sure this will be merged as is.

**Comment by nikobh** [comment]
> Other than that, this will introduce a major breaking change with the namechange for the original Radius entry, so I'm not sure this will be merged as is.

I understand. A suggestion could be to not change Radius - and add Radius B lav time as an additional tarrif.

**Comment by nikobh** [comment]
> Other than that, this will introduce a major breaking change with the namechange for the original Radius entry, so I'm not sure this will be merged as is.

The vast majority of customers has the C tariff, but some home organisations has their own electricity distribution network and they get the B tariff.

**Comment by MTrab** [comment]
Closed du to inactivity/no response

**Pull request closed without merging**
