### PR TITLE
Do not verify API SSL

### PR DESCRIPTION
**Pull request by MTrab**
To fix API SSL certificate validity errors/issues, disable SSL verification

### CODE REVIEW

**Comment by henriklund** [comment]
@MTrab, it may be worth considering if a configuration should be added allowing the enduser to actively deactivate SSL validation - should such a case like this occur in the future.

**Comment by exetico** [comment]
I agree with @henriklund ; make it optional, as part of the configuration. Pushing a update to simply ignore the API SSL validation are a bit... odd, even though Energinet was facing some issues with the certs (possibly?).

**Comment by henriknj** [comment]
Lets just get this change reverted, then we deal with adding a configuration option later.

**Comment by MTrab** [comment]
Will look into this when back from holiday - nothing will happen for at least one week

**Pull request merged**
