### PR TITLE
Removing Nordpool connector

### LINKED ISSUE #615: Nordpool API returns 404
### Describe the issue

Day ahead prices are no longer fetched from nordpool. Debug logging shows
`2024-10-15 15:18:03.171 ERROR (MainThread) [custom_components.energidataservice.connectors.nordpool] API returned error 404
2024-10-15 15:18:03.171 WARNING (MainThread) [custom_components.energidataservice.api] Couldn't get data from Energi Data Service, retrying in 5 minutes.`

The base-url used by the nordpool connector `https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=%s` no longer exists. From the looks of it a new api needs to be used. E.g. `https://dataportal-api.nordpoolgroup.com/api/DayAheadPrices?date=2024-10-16&market=DayAhead&deliveryArea=NL&currency=EUR` for NL.

### What version of Home Assistant Core has the issue?

core-2024.10.2

### What was the last working version of Home Assistant Core?

core-2024.10.2

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2024-10-15T13-18-23.123Z.log](https://github.com/user-attachments/files/17378912/home-assistant_energidataservice_2024-10-15T13-18-23.123Z.log)

### Anything in the logs that might be useful for us?

```txt
2024-10-15 15:18:03.171 ERROR (MainThread) [custom_components.energidataservice.connectors.nordpool] API returned error 404
2024-10-15 15:18:03.171 WARNING (MainThread) [custom_components.energidataservice.api] Couldn't get data from Energi Data Service, retrying in 5 minutes.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MTrab**
This is a breaking change as we are removing support for the following regions in this integration:

FI: Finland
EE: Estonia
LT: Lithuania
LV: Latvia
NO1: Oslo
NO3: Molde, Trondheim
NO4: Tromsø
NO5: Bergen
SE3: Stockholm
SE4: Malmö

This is done as part of future simplifications for this integration.

Essentially fixes #615

### CODE REVIEW

**Comment by enoch85** [comment]
FYI, it works! Why remove it? This is SE4 in Sweden.

Screenshot_2024-10-15-23-51-45-76_c3a231c25ed346e59462e84656a70e50

**Comment by enoch85** [comment]
Maybe some advice on how to bring ut back: https://github.com/custom-components/nordpool/commit/632ee5bb06e308e5c1639b03253c6f387ef55b18

**Comment by MTrab** [comment]
I need to simplify this integration, as it has become too difficult to maintain.
This is just step one of the simplification,  which unfortunately have removed alot of zones that are covered in the Nordpool integration

**Comment by enoch85** [comment]
>  become too difficult to maintain.

Ask for help then! :) Sorry, but the decision made here seems to be based on 1 single issue, but apparently it still works for me for example. 

I don't know anything about Python, but I can read code somewhat, and to me it seems like it's a few lines of code that needs changing. I.e the URL for the API, and changes to the some Country Codes.

For me personally, I use the entities from this plugin in a l o t of places in my HAOS. It would be a pain to change integration just because it's not maintained any more. For that reason I have asked around and are willing to pay the person who implements Nordpool back. If that's you, then fine. :)

**Comment by MTrab** [comment]
https://github.com/MTrab/energidataservice/pull/618

Not fully ready for release, still needs some work, if I get the time (time is not a luxury in my life, unfortunately)

**Comment by enoch85** [comment]
Where can I donate?

**Comment by MTrab** [comment]
https://www.buymeacoffee.com/mtrab

**Comment by enoch85** [comment]
ONce merged and working there will be some coffee coming your way! 🥳

**Pull request merged**
